### ISSUE TITLE
ProCam2D initialization issue when changing scenes

### ISSUE THREAD

**Issue by ilionic** [daz-b-like/ProCam2D_Godot3.x#1]
I've been testing the add-on, and it's great work! However, I've encountered an issue with ProCam2D initialization when changing scenes. Since I couldn't find specific documentation about adding ProCam2D node, I'll describe my current setup:

In my game scene, I have a ProCam2D node targeting the Player. (Is this the correct way to set up a ProCam2D node? If not, a minimal example would be helpful.)
Everything works fine within the game scene.
The problem occurs when I create another scene (e.g., a MainMenu UI) and use change_scene() to switch to the game scene. In this case, ProCam is not registered and initialized correctly.

Am I missing any steps in this process? Is there a specific way to handle ProCam2D initialization when changing scenes?
Thank you for your help!

**Comment by daz-b-like** [comment]
Hey there! I'm glad you like the plugin. I've been working on an update which fixes that and many other issues. I should be posting it by the weekend. For now, Try reassigning the player as target. in the ready script of the player and see if that works. If not kindly describe the exact behavior the camera has when you change scenes and the expected behavior.

**Comment by daz-b-like** [comment]
Hey @ilionic! I Rewrote the plugin for better performance and manageability. Check out the new update and docs to see the changes.

**Comment by ilionic** [comment]
hi @daz-b-like thanks for letting me know. Looking forward testing it! 
But unfortunately having plugin issues now: 

```
 res://addons/ProCam2D/scripts/core/nds/cam.gd:99 - Parse Error: The identifier "procam" isn't declared in the current scope.
 res://addons/ProCam2D/scripts/procam2d.gd:2 - Parse Error: Script isn't fully loaded (cyclic preload?): res://addons/ProCam2D/scripts/core/nds/cam.gd
 Failed parse script res://addons/ProCam2D/plugin.gd
 res://addons/ProCam2D/scripts/core/nds/cam.gd:99 
```

**Comment by daz-b-like** [comment]
@ilionic Sorry about that. I just fixed that. You can get the most recent upload [here](https://github.com/daz-b-like/ProCam2D_Godot3.x/archive/88deb2741a40e35566fe5b4928df90a6271469f8.zip)

**Comment by ilionic** [comment]
Thanks @daz-b-like ! 
Looks like it loads fine now, however I had to comment out bunch of my previous code since it seems like it's not longer based on singleton approach. So this would take me some time to refactor. Will update once it's done. Cheers

**Comment by ilionic** [comment]
Btw, tried to send smth via ko-fi but it didn't work. So pls consider some alternatives ( ie github sponsor )

**Comment by daz-b-like** [comment]
I'm glad to hear everything is working smoothly. I've rewritten the plugin for better optimization and performance, especially for low-end mobile devices. Future updates will be backward-compatible, ensuring no disruption to current projects.

For donations, most platforms, including GitHub Sponsors, don't support my region (Zambia). I've correctly set up my Ko-fi account, but if it still doesn't work, you can donate via direct transfer to a mobile wallet through [xoom.com](https://www.xoom.com/) using my Airtel Money account at +260773962393. Your support is greatly appreciated.

**Comment by ilionic** [comment]
Hey @daz-b-like FYI: I am testing new version and finding more issues with change_scene. While first time it works fine ( ie transition from MainMenu to Game ). After game is finished I have option to Restart ( change_scene to Game again ). And at this point ProCam2D stops reacting to changes and following PCamTarget.

**Comment by daz-b-like** [comment]
Hello @ilionic. I just fixed all issues related to scene changes and loading. Thanks for pointing that out. You can get the update [here](https://github.com/daz-b-like/ProCam2D_Godot3.x/archive/021b402450781c11cd3f97756acb97a55f4a3e09.zip). Feel free to report any bugs or to make any suggestions and feature requests.
